# Generated by Django 4.1.3 on 2022-11-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tipoUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='suscrito',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipoDeUsuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
