# Generated by Django 4.0.6 on 2022-11-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0005_alter_usuario_is_staff_alter_usuario_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.IntegerField()),
                ('patente', models.CharField(max_length=6, unique=True)),
                ('padron', models.CharField(max_length=17, unique=True)),
                ('color', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=20)),
                ('marca', models.TextField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
