# Generated by Django 4.1.3 on 2022-11-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0006_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='logo',
            field=models.FileField(default='', upload_to='static/images/logos'),
            preserve_default=False,
        ),
    ]
