# Generated by Django 4.1.3 on 2022-11-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0007_marca_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='logo',
            field=models.FileField(upload_to='cambiar_ruta_de_fichero'),
        ),
    ]
