# Generated by Django 4.1.3 on 2022-11-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0008_alter_marca_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.IntegerField()),
                ('idVehiculo', models.IntegerField()),
                ('fechaCita', models.DateField()),
                ('horaCita', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='marca',
            name='logo',
            field=models.FileField(upload_to='static/images/logos/'),
        ),
    ]
