# Generated by Django 4.1.3 on 2022-11-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0010_remove_marca_logo_marca_imgmarca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
