# Generated by Django 4.1.3 on 2022-11-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0011_cita_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(max_length=50, unique=True)),
                ('precioServicio', models.IntegerField()),
                ('descripcion', models.TextField(max_length=50)),
                ('activo', models.BooleanField()),
                ('tiempo', models.IntegerField()),
            ],
        ),
    ]
