# Generated by Django 4.1.3 on 2022-11-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0012_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='idServicio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
