# Generated by Django 4.1.3 on 2022-12-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0013_cita_idservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='imgServicio',
            field=models.ImageField(null=True, upload_to='servicio'),
        ),
    ]
