# Generated by Django 4.1.3 on 2022-12-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0014_servicios_imgservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='imgServicio',
            field=models.ImageField(null=True, upload_to='servicios'),
        ),
    ]
